const teamProfiles={
 kylene:{name:'Kylene Casey',initials:'KC',role:'Engagement Lead',subtitle:'Technology & Product Leader | AI-enabled Delivery | Program & Portfolio Management',bio:'Kylene Casey is a Florida-based Engagement Lead and Technology & Product Leader with more than 15 years of experience leading complex digital transformation, AI-enabled delivery, and portfolio management initiatives across public and private sectors. She specializes in translating business strategy into scalable, user-centered solutions, with expertise spanning GenAI strategy, SaaS modernization, product ownership, agile delivery, PMO development, and cross-functional team leadership.',experience:[['Engagement Leader & Solution Owner','Supported GenAI strategy and operating-model work for emergency-management clients, defining operating models and delivery rhythms for needs-based forecasting during emergency events and coordinating product, data, and engineering workstreams.'],['Strategic Product Owner & Portfolio Manager','Led roadmap, delivery structure, and GTM strategy to modernize an on-premises application into a scalable SaaS product; defined features, prioritized backlog, and developed the product roadmap.'],['Operational Excellence & Service Transformation','Architected a data-driven Customer Service Management program to boost engagement and retention and operationalized a succession-management model.'],['Civic Tech & Public Sector Delivery','More than 15 years managing large-scale civic-tech programs, building agile teams, and delivering scalable, user-centered solutions for federal, state, and local agencies.']],skills:['Project Management Professional','Six Sigma Black Belt','Certified Scrum Product Owner','Certified Scrum Master','Product Ownership','Program Development','Cross-functional Leadership','Process Improvement','Agile Coaching','Strategic Planning','Technical Program Delivery','AI & Data Enablement','IT Service Management']},
 darin:{name:'Darin Porter',initials:'DP',role:'Engagement Lead — Alternate',subtitle:'Engagement Lead | Program & Strategic Lead | Solution Owner',bio:'Darin Porter is a Florida-based Engagement Lead and Strategic Program Leader with more than 25 years of experience delivering large-scale business and technology transformation programs across multiple industries. He brings deep expertise in program leadership, strategic governance, cloud and platform modernization, vendor management, and PMO oversight.',experience:[['Program Lead / Solution Owner — Platform Integrator','Created executive-level plans and strategic vision coordinating internal resources, finance, and vendors for high-profile client deliverables across multiple large-scale platform transformations.'],['Strategic Owner — Thought Leadership','Created and implemented strategic governance programs and delivery checkpoints across leadership organizations, supporting network, software, and platform programs.'],['PMO Lead — Implementation & Release Management','Led national programs with oversight of budgets, planning, KPIs, readiness, and execution; established steering committees and executive transparency.']],skills:['Engagement & Program Leadership','Strategic Leadership','Cloud: GCP and AWS','MDM & Big Data','Salesforce Integration','Vendor Management','Deployment Planning','Revenue & Profit Optimization','Business & Systems Analysis','SDLC','Cybersecurity','Logistics Readiness']},
 erika:{name:'Erika Nolting Young',initials:'EN',role:'Commercial / GTM Lead — Alternate',subtitle:'Director, Market Solutions — Sales Strategy',bio:'Over 18 years in industry and consulting, Erika has gained experience and insights that uniquely enable her to help clients with business strategy, go-to-market strategy, revenue strategy and sales effectiveness, product strategy, and innovation strategy. She has worked with companies of all sizes from Fortune 50 to startup.',experience:[['Advancing Account Planning — Fortune 1000 Security Tech','Assessed account-planning processes and supporting technologies; synthesized stakeholder interviews and developed recommendations, comparative frameworks, and a prioritized roadmap.'],['GTM Assessment — Global Media Technology Company','Identified opportunity areas across target growth, sales, marketing, finance, and engineering; prioritized findings and developed a recommendations roadmap.'],['Seller Experience — Global Fintech Company','Mapped the seller experience from lead to renewal, prioritized pain points and solutions, and created a roadmap to improve seller effectiveness.']],skills:['GTM Strategy','Sales Strategy','Sales Operations','Sales Enablement','Seller Experience','Digital Strategy','Customer Strategy','Innovation Strategy','Business Strategy']},
 hunter:{name:'Hunter Brocato',initials:'HB',role:'Commercial / GTM Support',subtitle:'Customer-Led Growth Strategist',bio:'Hunter works with clients to design and mobilize experience-led strategies spanning marketing, sales, and service to unlock customer and business value.',experience:[['Open Enrollment Experience Strategy & Roadmap','Led a four-person cross-functional team developing strategy and roadmap to drive member growth and retention for a Fortune 5 health insurer.'],['Digital Transformation — Marketing & Sales','Co-led a multi-year digital transformation from strategy development through execution to drive 2x revenue-growth targets, supporting Lead-to-Opportunity, data management, and AI for Sales.'],['Cloud Contact Center Transformation','Advised a C-suite executive on a five-year business case and financial model for a $10M cloud-enabled transformation, then mobilized a six-person team for a regional bank.']],skills:['Business Case','Financial Modeling','Capability Assessment','Competitive Research','Customer Research','Journey Mapping','Process Optimization','Service Blueprinting','Solution Ownership']},
 jake:{name:'Jake Krause',initials:'JK',role:'Commercial / GTM Support',subtitle:'Senior Consultant — Digital & Customer Strategy',bio:'Jake has more than nine years of experience across marketing and sales roles, from Fortune 500 organizations to growth-stage startups, with deep expertise across B2B marketing, sales enablement, sales strategy, and digital strategy.',experience:[['Medical Device Manufacturer — Marketing & Sales Capability Roadmap','Led identification of process-improvement opportunities across lead generation, physician relationship management, interdepartment collaboration, and marketing/sales asset management, producing a prioritized three-year roadmap.'],['Experience Management — ABM Campaign Strategy','Developed an account-based marketing strategy, ideal-customer profile, asset inventory, and activation process to grow cross-sell pipeline in target accounts.'],['Health Insurance — GTM Playbook','Mapped the end-to-end GTM process, identified roadblocks and approvals, and created a reusable playbook across Sales, Product, Communication, and Marketing teams.']],skills:['Customer Strategy','B2B Strategy','Digital Strategy','Sales Enablement','Sales Process Improvement','Digital Media','Product Marketing','Product Management','Product Strategy','Marketing Capability Roadmap','GTM Strategy','Service Blueprint Design','User Research']}
};
const keyRows=[
 ['Engagement Lead','Kylene Casey','Alternate: Darin Porter','Overall accountability and primary ELT interface','kylene','leadership'],
 ['Commercial / GTM Lead','Amy Klein Da Costa','Alternate: Erika Nolting Young','Offering strategy, pricing, and commercialization','erika','commercial'],
 ['AEC Market Sector Lead','Hide Harashima','','Market-specific knowledge and buyer validation','','market'],
 ['Federal Defense Market Lead','CJ or XX','','Market-specific knowledge and buyer validation','','market'],
 ['Transportation Market Lead','Nate Higgins','','Market-specific knowledge and buyer validation','','market'],
 ['Aviation Market Lead','Peter Hammer','','Market-specific knowledge and buyer validation','','market'],
 ['Financial Modeling Lead','Benjamin Wei','','Revenue models, EBBIT analysis, and investment scenarios','','finance'],
 ['Technology Advisory Lead','Justin Tormey','','Technology architecture and platform advisory, solution feasibility, delivery-model implications, and AI/data, digital twin, and OT/cybersecurity considerations across prioritized offerings','','technology']
];
const additionalRows=[
 ['Accountable Executive','Dan Okray','','Senior leader responsible for leading the Slalom team, managing the relationship, and serving as the escalation point for Slalom and RS&H','','leadership'],
 ['Commercial / GTM Strategist','Maddie Goertzen','Alternates: Jake Krause, Jennifer Leong, Hunter Brocato','','jake','commercial'],
 ['Financial Analyst','Nofil Siddiqi','','','','finance'],
 ['Business Analyst','Rock Lee','','','','commercial']
];
const roleIcons={leadership:'◈',commercial:'↗',market:'◎',finance:'▥',technology:'⌘'};
function roleCards(rows,title){return `<section class="role-group"><div class="role-group-heading"><div><p class="eyebrow blue">${title}</p><h3>${rows.length} proposed roles</h3></div></div><div class="role-card-list">${rows.map((r,i)=>`<article class="role-card role-${r[5]}" data-category="${r[5]}"><button class="role-card-trigger" type="button" aria-expanded="false"><span class="role-icon" aria-hidden="true">${roleIcons[r[5]]||'•'}</span><span class="role-card-summary"><strong>${r[0]}</strong><small>${r[1]}${r[2]?` · ${r[2]}`:''}</small></span><span class="role-card-toggle">+</span></button><div class="role-card-panel"><div class="role-detail-grid"><div><span class="role-detail-label">Named individual</span><strong>${r[1]}</strong>${r[2]?`<p>${r[2]}</p>`:''}</div><div><span class="role-detail-label">Role description</span><p>${r[3]||'<span class="selection-pending">To be finalized</span>'}</p></div></div>${r[4]?`<button class="role-profile-link" type="button" data-profile="${r[4]}">View profile →</button>`:''}</div></article>`).join('')}</div></section>`}
function renderProfile(key){const p=teamProfiles[key];if(!p)return;document.querySelectorAll('.profile-selector').forEach(b=>b.classList.toggle('is-active',b.dataset.profile===key));document.querySelector('#profile-panel').innerHTML=`<div class="profile-identity"><div class="profile-photo placeholder-${key}"><span>${p.initials}</span></div><div><p class="profile-kicker">${p.role}</p><h3>${p.name}</h3><p class="profile-subtitle">${p.subtitle}</p></div></div><div class="profile-body"><section class="profile-about"><p class="profile-label">About</p><p>${p.bio}</p></section><section><p class="profile-label">Relevant experience</p><div class="experience-stack">${p.experience.map((e,i)=>`<article class="profile-experience color-${i+1}"><span>0${i+1}</span><div><h4>${e[0]}</h4><p>${e[1]}</p></div></article>`).join('')}</div></section><section><p class="profile-label">Skills</p><div class="skill-cloud">${p.skills.map((s,i)=>`<span class="skill-chip chip-${i%5+1}">${s}</span>`).join('')}</div></section></div>`}
function buildTeam(){const target=document.querySelector('#team-content');if(!target)return;const filters=[['all','All'],['leadership','Leadership'],['commercial','Commercial'],['market','Market'],['finance','Finance'],['technology','Technology']];target.innerHTML=`<div class="team-intro reveal"><p>Our multidisciplinary team brings deep expertise across AI governance, responsible AI, cybersecurity, data strategy, change management, and public sector operations, with ongoing collaboration and dedicated ownership of every deliverable from discovery through final presentation.</p></div><div class="role-overview"><div><strong>${keyRows.length}</strong><span>Key personnel</span></div><div><strong>${additionalRows.length}</strong><span>Additional roles</span></div><div><strong>${Object.keys(teamProfiles).length}</strong><span>Leadership profiles</span></div></div><div class="role-filters">${filters.map((f,i)=>`<button class="role-filter ${i===0?'is-active':''}" type="button" data-filter="${f[0]}">${f[1]}</button>`).join('')}</div>${roleCards(keyRows,'C.1 Named Key Personnel')}${roleCards(additionalRows,'Additional Roles')}<div class="team-explorer"><div class="team-explorer-heading"><p class="eyebrow blue">Leadership profiles</p><h3>Meet the team behind the engagement</h3><p>Select a profile to explore relevant experience and skills without leaving the proposal.</p></div><div class="profile-selectors">${Object.entries(teamProfiles).map(([k,p])=>`<button class="profile-selector" data-profile="${k}"><span class="selector-avatar placeholder-${k}">${p.initials}</span><span><strong>${p.name}</strong><small>${p.role}</small></span></button>`).join('')}</div><div id="profile-panel" class="profile-panel"></div></div>`;
 target.querySelectorAll('.role-card-trigger').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('.role-card');const open=card.classList.toggle('is-open');btn.setAttribute('aria-expanded',String(open));btn.querySelector('.role-card-toggle').textContent=open?'−':'+';}));
 target.querySelectorAll('.role-filter').forEach(btn=>btn.addEventListener('click',()=>{target.querySelectorAll('.role-filter').forEach(b=>b.classList.remove('is-active'));btn.classList.add('is-active');const filter=btn.dataset.filter;target.querySelectorAll('.role-card').forEach(card=>card.hidden=filter!=='all'&&card.dataset.category!==filter);}));
 target.querySelectorAll('[data-profile]').forEach(el=>el.addEventListener('click',()=>{renderProfile(el.dataset.profile);if(el.classList.contains('role-profile-link'))document.querySelector('.team-explorer').scrollIntoView({behavior:'smooth',block:'start'});}));
 renderProfile('kylene');
}
buildTeam();