(()=>{const rows=[{id:'governance',name:'Status & Governance'},{id:'workshops',name:'Workshops & Working Sessions'},{id:'mobilization-access',name:'Mobilization & Access'},{id:'baseline',name:'Baseline Assessment Validation Report'},{id:'market',name:'External Market Assessment'},{id:'offering',name:'Offering Strategy & Portfolio Prioritization'},{id:'gtm-document',name:'GTM Strategy Document'},{id:'financial-model',name:'Business & Financial Model'},{id:'readout-presentation',name:'Digital GTM Strategy Readout Presentation'}];
const item=(id,title,type,phase,row,weekStart,weekEnd,executiveVisible=false)=>({id,title,type,phase,row,weekStart,weekEnd,executiveVisible,summary:title});
const eleven={id:'accelerated',label:'11-Week Accelerated',shortLabel:'11 weeks',descriptor:'RFP-aligned accelerated schedule',tradeoff:'Faster path · concentrated stakeholder engagement · less schedule contingency',durationWeeks:11,kickoffDate:'2026-10-05',phases:[{id:'mobilization',name:'Mobilization',weekStart:1,weekEnd:2},{id:'assessment',name:'Assessment Validation',weekStart:3,weekEnd:4},{id:'gtm',name:'GTM Development',weekStart:5,weekEnd:7},{id:'financial',name:'Financial / Roadmap',weekStart:8,weekEnd:9},{id:'readout',name:'ELT Readout',weekStart:10,weekEnd:11}],rows,items:[
item('11-steering','Steering Meeting','Governance Milestone','mobilization','governance',2,2,true),item('11-risk-int','High Risk: Interviews','Midpoint Review','assessment','governance',3,3,true),item('11-status4','Status checkpoint','Governance Milestone','assessment','governance',4,4,true),item('11-status6','Status checkpoint','Governance Milestone','gtm','governance',6,6,true),item('11-risk-review','High Risk: Reviews','Midpoint Review','financial','governance',8,8,true),item('11-status9','Status checkpoint','Governance Milestone','financial','governance',9,9,true),item('11-risk-final','High Risk: Reviews','Midpoint Review','readout','governance',10,10,true),
item('11-kickoff','Kickoff · In Person','Workshop','mobilization','workshops',1,1,true),item('11-brand','Brand Alignment & Future Vision · Virtual','Workshop','mobilization','workshops',2,2,true),item('11-midpoint','Midpoint Findings Validation · In Person','Workshop','gtm','workshops',5,5,true),item('11-kt','Knowledge Transfer Session · Virtual','Workshop','readout','workshops',10,10,true),item('11-elt','ELT Readout · In Person','ELT Readout','readout','workshops',11,11,true),
item('11-mob','Kickoff, access & workplan · confirm scope, sponsors & success criteria · environment & data access · interview scheduling','Activity','mobilization','mobilization-access',1,2),
item('11-base','Interviews, capability inventory & gap analysis · stakeholder interviews · digital capability inventory · maturity scoring · operating-model, pricing & talent gaps · demand signals','Activity','assessment','baseline',2,4),item('11-base-review','CLIENT REVIEW · 2 ROUNDS · Baseline Assessment','Client Review','gtm','baseline',5,7,true),
item('11-market','Desk research, buyer interviews & market sizing · secondary & competitive research · recruit/field/synthesize buyer personas · TAM/SAM/SOM','Activity','assessment','market',2,4),item('11-market-review','CLIENT REVIEW · 2 ROUNDS · External Market Assessment','Client Review','gtm','market',5,7,true),
item('11-offering','Offering canvas, prioritization & pricing · client-problem mapping · capability maturity & strategic fit · ranked portfolio with rationale','Activity','gtm','offering',4,7),item('11-offering-review','CLIENT REVIEW · 2 ROUNDS · Offering Strategy & Portfolio Prioritization','Client Review','financial','offering',8,10,true),
item('11-gtm','Positioning, commercialization & enablement · GTM strategy & positioning · commercialization approach & major-account structure · sales-enablement framework · routes to market · partner/alliance strategy','Activity','gtm','gtm-document',5,7),item('11-gtm-review','CLIENT REVIEW · 2 ROUNDS · GTM Strategy','Client Review','financial','gtm-document',8,10,true),
item('11-fin','Scenario-based projections & ROI · pricing roadmap & strategic-plan draft · scenario modeling & ROI','Activity','gtm','financial-model',5,7),item('11-fin2','Revenue model & profit margin, Opex & Capex by offering','Activity','financial','financial-model',7,8),item('11-fin-review','CLIENT REVIEW · 2 ROUNDS · Business & Financial Model','Client Review','readout','financial-model',9,11,true),
item('11-readout','Synthesize, assemble deck & knowledge transfer · integrate assessment, strategy & financials into executive narrative · Digital GTM Strategic Plan document + ELT / Board presentation · FY28 implementation recommendation · KT plan & handover','ELT Readout','readout','readout-presentation',8,10,true),item('11-readout-review','CLIENT REVIEW · 2 ROUNDS · Final Deliverables','Client Review','readout','readout-presentation',10,11,true)]};
const fourteen={id:'lower-risk',label:'14-Working-Week Lower-Risk',shortLabel:'14 working weeks',descriptor:'Lower schedule-risk alternative',tradeoff:'More review capacity · two-week holiday pause · greater schedule resilience',durationWeeks:16,workingWeeks:14,kickoffDate:'2026-10-05',holidayWeeks:[12,13],phases:[{id:'mobilization',name:'Mobilization',weekStart:1,weekEnd:3},{id:'assessment',name:'Assessment Validation',weekStart:4,weekEnd:5},{id:'gtm',name:'GTM Development',weekStart:6,weekEnd:9},{id:'financial',name:'Financial / Roadmap',weekStart:10,weekEnd:11},{id:'prep',name:'ELT Prep',weekStart:12,weekEnd:13},{id:'readout',name:'ELT Readout',weekStart:14,weekEnd:16}],rows,items:[
item('14-steering','Steering Meeting','Governance Milestone','mobilization','governance',2,2,true),item('14-risk-int','High Risk: Interviews','Midpoint Review','mobilization','governance',3,3,true),item('14-status4','Status checkpoint','Governance Milestone','assessment','governance',4,4,true),item('14-status7','Status checkpoint','Governance Milestone','gtm','governance',7,7,true),item('14-risk-review','High Risk: Reviews','Midpoint Review','gtm','governance',8,8,true),item('14-status9','Status checkpoint','Governance Milestone','gtm','governance',9,9,true),item('14-status11','Status checkpoint','Governance Milestone','financial','governance',11,11,true),item('14-status14','Status checkpoint','Governance Milestone','readout','governance',14,14,true),
item('14-kickoff','Kickoff · In Person','Workshop','mobilization','workshops',1,1,true),item('14-brand','Brand Alignment & Future Vision · Virtual','Workshop','mobilization','workshops',2,2,true),item('14-midpoint','Midpoint Findings Validation · In Person','Workshop','gtm','workshops',5,5,true),item('14-kt','KT Session · Virtual','Workshop','readout','workshops',15,15,true),item('14-elt','ELT Readout · In Person','ELT Readout','readout','workshops',16,16,true),
item('14-mob','Kickoff & workplan · confirm scope, sponsors & success criteria · environment & data access · interview scheduling · desk-research baseline plan sign-off','Activity','mobilization','mobilization-access',1,3),
item('14-base','Interviews, capability inventory & gap analysis · stakeholder interviews · digital capability inventory · maturity scoring · operating-model, pricing & talent gaps · demand signals','Activity','assessment','baseline',2,5),item('14-base-review','CLIENT REVIEW · 2 ROUNDS · Baseline Assessment','Client Review','gtm','baseline',6,9,true),
item('14-market','Desk research, buyer interviews & market sizing · secondary & competitive research · recruit/field/synthesize buyer personas · TAM/SAM/SOM','Activity','assessment','market',2,5),item('14-market-review','CLIENT REVIEW · 2 ROUNDS · External Market Assessment','Client Review','gtm','market',6,9,true),
item('14-offering','Offering canvas, prioritization & pricing · offering canvas & scoring · client-problem mapping · capability maturity & strategic fit · ranked portfolio with rationale','Activity','gtm','offering',4,8),item('14-offering-review','CLIENT REVIEW · 2 ROUNDS · Offering Strategy','Client Review','gtm','offering',8,11,true),
item('14-gtm','Positioning, commercialization & enablement · GTM strategy & positioning by market · commercialization approach & major-account structure · sales-enablement framework & bundled routes to market · partner/alliance strategy','Activity','gtm','gtm-document',6,8),item('14-gtm-review','CLIENT REVIEW · 2 ROUNDS · GTM Strategy','Client Review','gtm','gtm-document',8,11,true),
item('14-fin','Scenario-based projections & ROI · pricing roadmap & strategic-plan draft · scenario modeling & ROI · pricing roadmap & strategic-plan draft','Activity','gtm','financial-model',6,8),item('14-fin2','Revenue model & profit margin, Opex & Capex by offering','Activity','gtm','financial-model',7,10),item('14-fin-review','CLIENT REVIEW · Business & Financial Model','Client Review','financial','financial-model',10,11,true),item('14-fin-final','CLIENT REVIEW · 1 ROUND · Offering Strategy + Financial Model','Client Review','readout','financial-model',14,16,true),
item('14-readout','Synthesize & assemble deck · integrate assessment, strategy & financials into executive narrative · Digital GTM Strategic Plan document + ELT / Board presentation · FY28 implementation recommendation · Knowledge Transfer Planning','ELT Readout','gtm','readout-presentation',8,11,true),item('14-readout-final','CLIENT REVIEW · 1 ROUND · ELT & KT','Client Review','readout','readout-presentation',14,16,true)]};
window.workplanData={projectTitle:'RS&H Digital GTM Strategy',defaultPlan:'accelerated',plans:{accelerated:eleven,'lower-risk':fourteen}};})();